export const LOGIN= 'LOGIN'
export const LOGINOUT= 'LOGINOUT'
//export const USERNAME= 'USERNAME'
export const BOOK_ADD= 'BOOK_ADD'
export const BOOK_DELETE= 'BOOK_DELETE'
export const BOOK_UPDATE= 'BOOK_UPDATE'
export const BUY_BOOK= 'BUY_BOOK'
export const CANCEL_BOOK= 'CANCEL_BOOK'
